name: CI

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.23.3'
      
    - name: Tidy modules
      run: go mod tidy

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3

    - name: Turnstyle
      if: ${{ github.event_name == 'push' && github.ref == 'refs/head/trunk' }}
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image
      run: docker build --file Dockerfile --tag tod:latest .
    
    - name: Push to GitHub
      if: ${{ github.repository == 'holedaemon/tod' && github.event_name == 'push' && github.ref == 'refs/head/trunk' }}
      run: |
        echo '${{ secrets.GITHUB_TOKEN }}' | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        docker tag tod:latest ghcr.io/holedaemon/tod:latest
        docker push ghcr.io/holedaemon/tod:latest